[default_settings]

current_density_to_calculate_overpotential_at = [ -5, -10, -15 ]
line_potential = [0.1, 0.2, 0.15]
time_chrono = 50
surface_area = 0.01
reference_potential = 0.21
geometrical_area = 0.070686

[units_mapping]
"E vs RHE" = "[V]"
"E_iR vs RHE" = "[V]"
J_GEO = "[A]"
T = "[s]"

[user_profiles]

    [user_profiles.profile1]

        [user_profiles.profile1.Global]

            surface_area = 1
            reference_potential = 0.21 #The potential of the reference electrode (taken to be Ag/AgCl)
            current_density_to_calculate_overpotential_at = [ -5, -10, -15 ] #The overpotentials are reported at specific current densities
            uncompensated_resistance = 0 #Needed for iR-drop correction
        
        [user_profiles.profile1.units_mapping]

            "E vs RHE" = "[V]"
            "E_iR vs RHE" = "[V]"
            J_GEO = "[A]"
            T = "[s]"

        [user_profiles.profile1.Experiments]

            [user_profiles.profile1.Experiments.Chronoamperometry]

                time_chrono = [-1, 120, 'pick'] #Add a functionality 'pick' to ask the user at which time stamp the current needs to be calculated

            [user_profiles.profile1.Experiments.ECSA]

                line_potential = [0.1, 0.2, 0.15] #Add an option to select for each measurement, same for time_chrono and other parameters
                curve_to_calculate = [0, -1, 'average'] #Specfies which curve to process and save in case of ECSA measurements
        


        
