[input_messages]

    time_not_in_range = 'Provided time not in range! Maximum time is {time_in_seconds} s. Please provide new time in seconds: '
    save_name = 'Please input the Excel output name: '
    cycle_input = 'Input the cycle or press enter for none: '
    file_name_input = 'Input name of file. The program will try to find all experiments matching the string: '
    object_type_input = 'Input the object type: '

[processing_messages]
    processing_data = 'Saving data of {experiment_type} of cycle: {cycle}...'
    processing_done =  'Saving data of {experiment_type} of cycle: {cycle}... DONE!'